var searchData=
[
  ['gap_20address_20types',['GAP Address Types',['../group___g_a_p___a_d_d_r___t_y_p_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20advertisment_20data_20types',['GAP Advertisment Data Types',['../group___g_a_p___a_d_t_y_p_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20adtype_20flags_20discovery_20modes',['GAP ADTYPE Flags Discovery Modes',['../group___g_a_p___a_d_t_y_p_e___f_l_a_g_s___m_o_d_e_s.html',1,'']]],
  ['gap_20advertisement_20channel_20map',['GAP Advertisement Channel Map',['../group___g_a_p___a_d_v_c_h_a_n___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20advertising_20report_20event_20types',['GAP Advertising Report Event Types',['../group___g_a_p___a_d_v_e_r_t_i_s_e_m_e_n_t___r_e_p_o_r_t___t_y_p_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20advertising_20event_20types',['GAP Advertising Event Types',['../group___g_a_p___a_d_v_e_r_t_i_s_e_m_e_n_t___t_y_p_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20api_20functions',['GAP API Functions',['../group___g_a_p___a_p_i.html',1,'']]],
  ['gap_20appearance_20values',['GAP Appearance Values',['../group___g_a_p___a_p_p_e_a_r_a_n_c_e___v_a_l_u_e_s.html',1,'']]],
  ['gap_20special_20connection_20handles',['GAP Special Connection Handles',['../group___g_a_p___c_o_n_n___h_a_n_d_l_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20device_20discovery_20modes',['GAP Device Discovery Modes',['../group___g_a_p___d_e_v_d_i_s_c___m_o_d_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20advertiser_20filter_20scan_20parameters',['GAP Advertiser Filter Scan Parameters',['../group___g_a_p___f_i_l_t_e_r___p_o_l_i_c_y___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20message_20ids',['GAP Message IDs',['../group___g_a_p___m_s_g___e_v_e_n_t___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20parameter_20ids',['GAP Parameter IDs',['../group___g_a_p___p_a_r_a_m_e_t_e_r___i_d___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20profile_20roles',['GAP Profile Roles',['../group___g_a_p___p_r_o_f_i_l_e___r_o_l_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20white_20list_20options',['GAP White List Options',['../group___g_a_p___w_h_i_t_e_l_i_s_t___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20bond_20manager_20constants',['GAP Bond Manager Constants',['../group___g_a_p_b_o_n_d___c_o_n_s_t_a_n_t_s___n_a_m_e.html',1,'']]],
  ['gap_20bond_20manager_20i_2fo_20capabilities',['GAP Bond Manager I/O Capabilities',['../group___g_a_p_b_o_n_d___i_o___c_a_p___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20bond_20manager_20key_20distribution',['GAP Bond Manager Key Distribution',['../group___g_a_p_b_o_n_d___k_e_y___d_i_s_t___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20bond_20manager_20pairing_20modes',['GAP Bond Manager Pairing Modes',['../group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___m_o_d_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20bond_20manager_20pairing_20states',['GAP Bond Manager Pairing States',['../group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___s_t_a_t_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gap_20bond_20manager_20parameters',['GAP Bond Manager Parameters',['../group___g_a_p_b_o_n_d___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html',1,'']]],
  ['gap_20central_20role_20parameters',['GAP Central Role Parameters',['../group___g_a_p_c_e_n_t_r_a_l_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html',1,'']]],
  ['gap_20observer_20role_20parameters',['GAP Observer Role Parameters',['../group___g_a_p_o_b_s_e_r_v_e_r_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html',1,'']]],
  ['gap_20role_20parameters',['GAP Role Parameters',['../group___g_a_p_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html',1,'']]],
  ['gap_20bond_20manager_20api_20functions',['GAP Bond Manager API Functions',['../group___g_a_p_r_o_l_e_s___b_o_n_d_m_g_r___a_p_i.html',1,'']]],
  ['gap_20broadcaster_20role_20api_20functions',['GAP Broadcaster Role API Functions',['../group___g_a_p_r_o_l_e_s___b_r_o_a_d_c_a_s_t_e_r___a_p_i.html',1,'']]],
  ['gap_20peripheral_20role_20api_20functions',['GAP Peripheral Role API Functions',['../group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___a_p_i.html',1,'']]],
  ['gap_20peripheral_20_2b_20broadcaster_20role_20api_20functions',['GAP Peripheral + Broadcaster Role API Functions',['../group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___b_r_o_a_d_c_a_s_t_e_r___a_p_i.html',1,'']]],
  ['gatt_20client_20api_20functions',['GATT Client API Functions',['../group___g_a_t_t___c_l_i_e_n_t___a_p_i.html',1,'']]],
  ['gatt_20client_20characteristic_20configuration_20bit_20fields',['GATT Client Characteristic Configuration Bit Fields',['../group___g_a_t_t___c_l_i_e_n_t___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20client_20sub_2dprocedure_20api_20functions',['GATT Client Sub-Procedure API Functions',['../group___g_a_t_t___c_l_i_e_n_t___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html',1,'']]],
  ['gatt_20encryption_20key_20size',['GATT Encryption Key Size',['../group___g_a_t_t___e_n_c_r_y_p_t___k_e_y___s_i_z_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20characteristic_20extended_20properties_20bit_20fields',['GATT Characteristic Extended Properties Bit Fields',['../group___g_a_t_t___e_x_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20flow_20control_20api_20functions',['GATT Flow Control API Functions',['../group___g_a_t_t___f_l_o_w___c_t_r_l___a_p_i.html',1,'']]],
  ['gatt_20characteristic_20format_20types',['GATT Characteristic Format Types',['../group___g_a_t_t___f_o_r_m_a_t___t_y_p_e_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20maximum_20attribute_20value_20length',['GATT Maximum Attribute Value Length',['../group___g_a_t_t___m_a_x___a_t_t_r___s_i_z_e___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20bluetooth_20namespace_20descriptions',['GATT Bluetooth Namespace Descriptions',['../group___g_a_t_t___n_s___b_t___d_e_s_c___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20namespace_20types',['GATT Namespace Types',['../group___g_a_t_t___n_s___t_y_p_e_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20maximum_20number_20of_20prepare_20writes',['GATT Maximum Number of Prepare Writes',['../group___g_a_t_t___n_u_m___p_r_e_p_a_r_e___w_r_i_t_e_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20attribute_20access_20permissions_20bit_20fields',['GATT Attribute Access Permissions Bit Fields',['../group___g_a_t_t___p_e_r_m_i_t___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20characteristic_20properties_20bit_20fields',['GATT Characteristic Properties Bit Fields',['../group___g_a_t_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20server_20app_20api_20functions',['GATT Server App API Functions',['../group___g_a_t_t___s_e_r_v___a_p_p___a_p_i.html',1,'']]],
  ['gatt_20server_20app_20callback_20api_20functions',['GATT Server App Callback API Functions',['../group___g_a_t_t___s_e_r_v___a_p_p___c_b___a_p_i.html',1,'']]],
  ['gatt_20server_20characteristic_20configuration_20bit_20fields',['GATT Server Characteristic Configuration Bit Fields',['../group___g_a_t_t___s_e_r_v___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20server_20message_20ids',['GATT Server Message IDs',['../group___g_a_t_t___s_e_r_v___m_s_g___e_v_e_n_t___d_e_f_i_n_e_s.html',1,'']]],
  ['gatt_20server_20api_20functions',['GATT Server API Functions',['../group___g_a_t_t___s_e_r_v_e_r___a_p_i.html',1,'']]],
  ['gatt_20server_20sub_2dprocedure_20api_20functions',['GATT Server Sub-Procedure API Functions',['../group___g_a_t_t___s_e_r_v_e_r___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html',1,'']]]
];
