var modules =
[
    [ "ATT Methods", "group___a_t_t___m_e_t_h_o_d___d_e_f_i_n_e_s.html", "group___a_t_t___m_e_t_h_o_d___d_e_f_i_n_e_s" ],
    [ "ATT Error Codes", "group___a_t_t___e_r_r___c_o_d_e___d_e_f_i_n_e_s.html", "group___a_t_t___e_r_r___c_o_d_e___d_e_f_i_n_e_s" ],
    [ "ATT Client API Functions", "group___a_t_t___c_l_i_e_n_t___a_p_i.html", "group___a_t_t___c_l_i_e_n_t___a_p_i" ],
    [ "ATT Server API Functions", "group___a_t_t___s_e_r_v_e_r___a_p_i.html", "group___a_t_t___s_e_r_v_e_r___a_p_i" ],
    [ "BLE Common Defines", "group___b_l_e___c_o_m_m_o_n___d_e_f_i_n_e_s.html", "group___b_l_e___c_o_m_m_o_n___d_e_f_i_n_e_s" ],
    [ "BLE GAP Constants and Structures", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html", "group___b_l_e___g_a_p___d_e_f_i_n_e_s" ],
    [ "GAP API Functions", "group___g_a_p___a_p_i.html", "group___g_a_p___a_p_i" ],
    [ "GATT Attribute Access Permissions Bit Fields", "group___g_a_t_t___p_e_r_m_i_t___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___p_e_r_m_i_t___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Maximum Number of Prepare Writes", "group___g_a_t_t___n_u_m___p_r_e_p_a_r_e___w_r_i_t_e_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___n_u_m___p_r_e_p_a_r_e___w_r_i_t_e_s___d_e_f_i_n_e_s" ],
    [ "GATT Encryption Key Size", "group___g_a_t_t___e_n_c_r_y_p_t___k_e_y___s_i_z_e___d_e_f_i_n_e_s.html", "group___g_a_t_t___e_n_c_r_y_p_t___k_e_y___s_i_z_e___d_e_f_i_n_e_s" ],
    [ "GATT Maximum Attribute Value Length", "group___g_a_t_t___m_a_x___a_t_t_r___s_i_z_e___d_e_f_i_n_e_s.html", "group___g_a_t_t___m_a_x___a_t_t_r___s_i_z_e___d_e_f_i_n_e_s" ],
    [ "GATT Client API Functions", "group___g_a_t_t___c_l_i_e_n_t___a_p_i.html", "group___g_a_t_t___c_l_i_e_n_t___a_p_i" ],
    [ "GATT Server API Functions", "group___g_a_t_t___s_e_r_v_e_r___a_p_i.html", "group___g_a_t_t___s_e_r_v_e_r___a_p_i" ],
    [ "GATT Server Sub-Procedure API Functions", "group___g_a_t_t___s_e_r_v_e_r___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html", "group___g_a_t_t___s_e_r_v_e_r___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i" ],
    [ "GATT Client Sub-Procedure API Functions", "group___g_a_t_t___c_l_i_e_n_t___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html", "group___g_a_t_t___c_l_i_e_n_t___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i" ],
    [ "GATT Flow Control API Functions", "group___g_a_t_t___f_l_o_w___c_t_r_l___a_p_i.html", "group___g_a_t_t___f_l_o_w___c_t_r_l___a_p_i" ],
    [ "SM I/O Capabilities", "group___s_m___i_o___c_a_p___d_e_f_i_n_e_s.html", "group___s_m___i_o___c_a_p___d_e_f_i_n_e_s" ],
    [ "SM Passkey Types (Bit Masks)", "group___s_m___p_a_s_s_k_e_y___t_y_p_e___d_e_f_i_n_e_s.html", "group___s_m___p_a_s_s_k_e_y___t_y_p_e___d_e_f_i_n_e_s" ],
    [ "SM AuthReq Bonding Flags", "group___s_m___b_o_n_d_i_n_g___f_l_a_g_s___d_e_f_i_n_e_s.html", "group___s_m___b_o_n_d_i_n_g___f_l_a_g_s___d_e_f_i_n_e_s" ],
    [ "Security Manager API Functions", "group___s_m___a_p_i.html", "group___s_m___a_p_i" ],
    [ "HAL Types", "group___h_a_l___t_y_p_e_s.html", "group___h_a_l___t_y_p_e_s" ],
    [ "GATT Server Message IDs", "group___g_a_t_t___s_e_r_v___m_s_g___e_v_e_n_t___d_e_f_i_n_e_s.html", "group___g_a_t_t___s_e_r_v___m_s_g___e_v_e_n_t___d_e_f_i_n_e_s" ],
    [ "GATT Characteristic Properties Bit Fields", "group___g_a_t_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Characteristic Extended Properties Bit Fields", "group___g_a_t_t___e_x_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___e_x_t___p_r_o_p___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Client Characteristic Configuration Bit Fields", "group___g_a_t_t___c_l_i_e_n_t___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___c_l_i_e_n_t___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Server Characteristic Configuration Bit Fields", "group___g_a_t_t___s_e_r_v___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___s_e_r_v___c_f_g___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Characteristic Format Types", "group___g_a_t_t___f_o_r_m_a_t___t_y_p_e_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___f_o_r_m_a_t___t_y_p_e_s___d_e_f_i_n_e_s" ],
    [ "GATT Namespace Types", "group___g_a_t_t___n_s___t_y_p_e_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___n_s___t_y_p_e_s___d_e_f_i_n_e_s" ],
    [ "GATT Bluetooth Namespace Descriptions", "group___g_a_t_t___n_s___b_t___d_e_s_c___d_e_f_i_n_e_s.html", "group___g_a_t_t___n_s___b_t___d_e_s_c___d_e_f_i_n_e_s" ],
    [ "GATT Server App Callback API Functions", "group___g_a_t_t___s_e_r_v___a_p_p___c_b___a_p_i.html", "group___g_a_t_t___s_e_r_v___a_p_p___c_b___a_p_i" ],
    [ "GATT Server App API Functions", "group___g_a_t_t___s_e_r_v___a_p_p___a_p_i.html", "group___g_a_t_t___s_e_r_v___a_p_p___a_p_i" ],
    [ "GAP Role Parameters", "group___g_a_p_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "GAP Broadcaster Role API Functions", "group___g_a_p_r_o_l_e_s___b_r_o_a_d_c_a_s_t_e_r___a_p_i.html", "group___g_a_p_r_o_l_e_s___b_r_o_a_d_c_a_s_t_e_r___a_p_i" ],
    [ "GAP Central Role Parameters", "group___g_a_p_c_e_n_t_r_a_l_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_c_e_n_t_r_a_l_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "Central Profile API Functions", "group___c_e_n_t_r_a_l___p_r_o_f_i_l_e___a_p_i.html", "group___c_e_n_t_r_a_l___p_r_o_f_i_l_e___a_p_i" ],
    [ "GAP Bond Manager Constants", "group___g_a_p_b_o_n_d___c_o_n_s_t_a_n_t_s___n_a_m_e.html", null ],
    [ "GAP Bond Manager Parameters", "group___g_a_p_b_o_n_d___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_b_o_n_d___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "GAP Bond Manager Pairing Modes", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___m_o_d_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___m_o_d_e___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager I/O Capabilities", "group___g_a_p_b_o_n_d___i_o___c_a_p___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___i_o___c_a_p___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager Key Distribution", "group___g_a_p_b_o_n_d___k_e_y___d_i_s_t___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___k_e_y___d_i_s_t___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager Pairing States", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___s_t_a_t_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___s_t_a_t_e___d_e_f_i_n_e_s" ],
    [ "Pairing failure status values", "group___s_m_p___p_a_i_r_i_n_g___f_a_i_l_e_d___d_e_f_i_n_e_s.html", "group___s_m_p___p_a_i_r_i_n_g___f_a_i_l_e_d___d_e_f_i_n_e_s" ],
    [ "Bonding Failure Actions", "group___g_a_p_b_o_n_d___b_o_n_d_i_n_g___f_a_i_l_u_r_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___b_o_n_d_i_n_g___f_a_i_l_u_r_e___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager API Functions", "group___g_a_p_r_o_l_e_s___b_o_n_d_m_g_r___a_p_i.html", "group___g_a_p_r_o_l_e_s___b_o_n_d_m_g_r___a_p_i" ],
    [ "GAP Observer Role Parameters", "group___g_a_p_o_b_s_e_r_v_e_r_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_o_b_s_e_r_v_e_r_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "Observer Profile API Functions", "group___o_b_s_e_r_v_e_r___p_r_o_f_i_l_e___a_p_i.html", "group___o_b_s_e_r_v_e_r___p_r_o_f_i_l_e___a_p_i" ],
    [ "GAP Peripheral Role API Functions", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___a_p_i.html", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___a_p_i" ],
    [ "GAP Peripheral + Broadcaster Role API Functions", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___b_r_o_a_d_c_a_s_t_e_r___a_p_i.html", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___b_r_o_a_d_c_a_s_t_e_r___a_p_i" ],
    [ "Module_usb_firmware_library_config", "group__module__usb__firmware__library__config.html", "group__module__usb__firmware__library__config" ],
    [ "USB Interrupt (usbirq)", "group__module__usb__interrupt.html", "group__module__usb__interrupt" ],
    [ "USB Suspend (usbsusp)", "group__module__usb__suspend.html", "group__module__usb__suspend" ],
    [ "USB Descriptor Parser (usbdp)", "group__module__usb__descriptor__parser.html", "group__module__usb__descriptor__parser" ],
    [ "USB Framework (usbfw)", "group__module__usb__framework.html", "group__module__usb__framework" ],
    [ "USB Standard Requests (usbsr)", "group__module__usb__standard__requests.html", "group__module__usb__standard__requests" ]
];